/**
 * Register Keepers Script
 *
 * This script:
 * 1. Wraps IND to WIND for each keeper
 * 2. Approves KeeperRegistry to spend WIND
 * 3. Reads BLS G2 public keys from keeper key files
 * 4. Registers keepers on-chain
 *
 * IMPORTANT: Keepers must have generated their BLS keys first by running the keeper binary.
 * The BLS public key is 128 bytes (G2 point) stored in data/bls_key_<instance_id>.json
 */

import { createWalletClient, createPublicClient, http, parseEther, formatEther, encodeFunctionData, toHex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Chain config
const RPC_URL = process.env.RPC_URL || "http://localhost:33010";
const CHAIN_ID = 111222333;

// Contract addresses (VPS2 deployment 2026-02-03)
const WIND_ADDRESS = "0x4e5b65FB12d4165E22f5861D97A33BA45c006114" as const;
const KEEPER_REGISTRY_ADDRESS = "0xE80FB0E8974EFE237fEf83B0df470664fc51fa99" as const;

// Keeper private keys (dev3, dev4, dev5)
const KEEPER_KEYS = [
  "0x237112963af91b42ca778fbe434a819b7e862cd025be3c86ce453bdd3e633165", // dev3
  "0xdbd4bf6a5edb48b1819a2e94920c156ff8296670d5df72e4b8a22df0b6ce573d", // dev4
  "0xae804cd43a8471813628b123189674469b92e3874674e540b9567e9e986d394d", // dev5
];

const KEEPER_INSTANCE_IDS = ["keeper1", "keeper2", "keeper3"];

const KEEPER_IPS = [
  "127.0.0.1:5001",
  "127.0.0.1:5002",
  "127.0.0.1:5003",
];

// Min stake: 100 WIND
const MIN_STAKE = parseEther("100");

// ABIs
const WIND_ABI = [
  {
    name: "deposit",
    type: "function",
    inputs: [],
    outputs: [],
    stateMutability: "payable",
  },
  {
    name: "approve",
    type: "function",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    name: "balanceOf",
    type: "function",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
] as const;

const KEEPER_REGISTRY_ABI = [
  {
    name: "registerKeeper",
    type: "function",
    inputs: [
      { name: "ip", type: "bytes32" },
      { name: "blsPubkey", type: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    name: "isActiveKeeper",
    type: "function",
    inputs: [{ name: "addr", type: "address" }],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    name: "getActiveKeeperCount",
    type: "function",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
] as const;

// Chain definition
const indexL3 = {
  id: CHAIN_ID,
  name: "Index L3",
  nativeCurrency: { name: "IND", symbol: "IND", decimals: 18 },
  rpcUrls: { default: { http: [RPC_URL] } },
} as const;

/**
 * Read BLS public key from keeper's key file
 * The key file is generated by the Rust keeper and contains a 128-byte G2 public key
 */
function readKeeperBlsPubkey(instanceId: string): string | null {
  // Try multiple paths for the key file
  const possiblePaths = [
    // Local development
    path.join(__dirname, "..", "..", "keeper", "data", `bls_key_${instanceId}.json`),
    path.join(__dirname, "..", "data", `bls_key_${instanceId}.json`),
    // Docker/VPS paths
    `/home/max/agiarena/keeper/data/bls_key_${instanceId}.json`,
    `/data/bls_key_${instanceId}.json`,
  ];

  for (const keyPath of possiblePaths) {
    try {
      if (fs.existsSync(keyPath)) {
        const content = fs.readFileSync(keyPath, "utf-8");
        const keyFile = JSON.parse(content);

        // Validate public key length (128 bytes = 256 hex chars, possibly with 0x prefix)
        let pubkey = keyFile.public_key as string;
        if (!pubkey.startsWith("0x")) {
          pubkey = "0x" + pubkey;
        }

        const pubkeyBytes = (pubkey.length - 2) / 2;
        if (pubkeyBytes !== 128) {
          console.log(`  Warning: BLS pubkey in ${keyPath} is ${pubkeyBytes} bytes, expected 128`);
          continue;
        }

        console.log(`  Found BLS key file: ${keyPath}`);
        return pubkey;
      }
    } catch (e) {
      // Continue to next path
    }
  }

  return null;
}

async function main() {
  console.log("=== Keeper Registration Script ===\n");
  console.log(`RPC: ${RPC_URL}`);
  console.log(`WIND Token: ${WIND_ADDRESS}`);
  console.log(`KeeperRegistry: ${KEEPER_REGISTRY_ADDRESS}`);
  console.log(`Min Stake: ${formatEther(MIN_STAKE)} WIND\n`);
  console.log("NOTE: Keepers must generate their BLS keys first by running the keeper binary.");
  console.log("      BLS public keys are 128 bytes (G2 point).\n");

  const publicClient = createPublicClient({
    chain: indexL3,
    transport: http(RPC_URL),
  });

  // Check chain connection
  const chainId = await publicClient.getChainId();
  console.log(`Connected to chain: ${chainId}\n`);

  // Store registered keepers for summary
  const registered: { address: string; ip: string; pubkeyPreview: string }[] = [];

  for (let i = 0; i < KEEPER_KEYS.length; i++) {
    const privateKey = KEEPER_KEYS[i] as `0x${string}`;
    const instanceId = KEEPER_INSTANCE_IDS[i];
    const ip = KEEPER_IPS[i];
    const account = privateKeyToAccount(privateKey);

    console.log(`\n--- Keeper ${i + 1}: ${account.address} (${instanceId}) ---`);

    const walletClient = createWalletClient({
      account,
      chain: indexL3,
      transport: http(RPC_URL),
    });

    // Check if already registered
    const isActive = await publicClient.readContract({
      address: KEEPER_REGISTRY_ADDRESS,
      abi: KEEPER_REGISTRY_ABI,
      functionName: "isActiveKeeper",
      args: [account.address],
    });

    if (isActive) {
      console.log(`  Already registered and active!`);
      continue;
    }

    // Read BLS pubkey from keeper's key file
    const blsPubkeyHex = readKeeperBlsPubkey(instanceId);
    if (!blsPubkeyHex) {
      console.log(`  ERROR: BLS key file not found for ${instanceId}`);
      console.log(`  Run the keeper first to generate the BLS key, then re-run this script.`);
      continue;
    }

    console.log(`  BLS pubkey (G2, 128 bytes): ${blsPubkeyHex.slice(0, 34)}...${blsPubkeyHex.slice(-8)}`);

    // Check native balance
    const nativeBalance = await publicClient.getBalance({ address: account.address });
    console.log(`  Native IND balance: ${formatEther(nativeBalance)}`);

    // Check WIND balance
    const windBalance = await publicClient.readContract({
      address: WIND_ADDRESS,
      abi: WIND_ABI,
      functionName: "balanceOf",
      args: [account.address],
    });
    console.log(`  WIND balance: ${formatEther(windBalance)}`);

    // If WIND balance < MIN_STAKE, wrap some IND
    if (windBalance < MIN_STAKE) {
      const wrapAmount = MIN_STAKE - windBalance + parseEther("1"); // Extra for gas
      console.log(`  Wrapping ${formatEther(wrapAmount)} IND to WIND...`);

      if (nativeBalance < wrapAmount) {
        console.log(`  ERROR: Insufficient IND balance to wrap!`);
        continue;
      }

      const wrapTx = await walletClient.sendTransaction({
        to: WIND_ADDRESS,
        value: wrapAmount,
        data: encodeFunctionData({
          abi: WIND_ABI,
          functionName: "deposit",
        }),
      });
      console.log(`  Wrap tx: ${wrapTx}`);
      await publicClient.waitForTransactionReceipt({ hash: wrapTx });
      console.log(`  Wrapped!`);
    }

    // Approve KeeperRegistry
    console.log(`  Approving KeeperRegistry...`);
    const approveTx = await walletClient.writeContract({
      address: WIND_ADDRESS,
      abi: WIND_ABI,
      functionName: "approve",
      args: [KEEPER_REGISTRY_ADDRESS, MIN_STAKE],
    });
    console.log(`  Approve tx: ${approveTx}`);
    await publicClient.waitForTransactionReceipt({ hash: approveTx });

    // Convert IP to bytes32
    const ipBytes32 = toHex(new TextEncoder().encode(ip).slice(0, 32), { size: 32 });
    console.log(`  IP bytes32: ${ipBytes32}`);

    // Register keeper
    console.log(`  Registering keeper with 128-byte G2 BLS pubkey...`);
    try {
      const registerTx = await walletClient.writeContract({
        address: KEEPER_REGISTRY_ADDRESS,
        abi: KEEPER_REGISTRY_ABI,
        functionName: "registerKeeper",
        args: [ipBytes32 as `0x${string}`, blsPubkeyHex as `0x${string}`],
      });
      console.log(`  Register tx: ${registerTx}`);
      await publicClient.waitForTransactionReceipt({ hash: registerTx });
      console.log(`  ✓ Keeper ${i + 1} registered!`);

      registered.push({
        address: account.address,
        ip: ip,
        pubkeyPreview: `${blsPubkeyHex.slice(0, 34)}...${blsPubkeyHex.slice(-8)}`,
      });
    } catch (error) {
      console.log(`  ERROR: ${(error as Error).message}`);
    }
  }

  // Final status
  console.log("\n=== Final Status ===");
  const activeCount = await publicClient.readContract({
    address: KEEPER_REGISTRY_ADDRESS,
    abi: KEEPER_REGISTRY_ABI,
    functionName: "getActiveKeeperCount",
  });
  console.log(`Active keepers: ${activeCount}`);

  if (registered.length > 0) {
    console.log("\nNewly Registered Keepers:");
    registered.forEach((k, i) => {
      console.log(`  ${i + 1}. ${k.address}`);
      console.log(`     IP: ${k.ip}`);
      console.log(`     BLS: ${k.pubkeyPreview}`);
    });
  }
}

main().catch(console.error);
